#基本信息
site_name: TensorTR
site_description: R^2 TesnorRT 非官方中文文档
site_author: R^2
site_url: http://tenosrrt.doc.zhiliao.ink
strict: false
#版权信息
copyright: 'Copyright &copy; 2022 R^2'
#目录
nav:
  - 简介:
    - "R^2 TensorRT": index.md
    - "关于本项目": about/关于本项目.md
    - "如何参与": about/如何参与.md
  - "快速入门指南": 快速入门指南.md

#Git
#repo_url: https://github.com/KunMengcode/knowledge-base
# 主题
theme:
  name: material
  language: zh
  logo: 'logo.png'
  favicon: 'icon.png'
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: black


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - search:
        lang:
            - en
            - ja
        separator: '[\s\-\.]+'